import { getSoilHistory } from '@/lib/getHistory';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';

export async function exportSoilHistoryPDF() {
  // Get the same 30 readings used by your chart
  const history = await getSoilHistory(30);

  if (!history || history.length === 0) {
    throw new Error('No soil history available.');
  }

  const rows = history
    .map((row) => {
      const date = new Date(row.created_at).toLocaleString();

      return `
        <tr>
          <td>${date}</td>
          <td>${row.nitrogen ?? '-'} mg/kg</td>
          <td>${row.phosphorus ?? '-'} mg/kg</td>
          <td>${row.potassium ?? '-'} mg/kg</td>
          <td>${row.ph ?? '-'}</td>
          <td>${row.soil_moisture ?? '-'}%</td>
          <td>${row.humidity ?? '-'}%</td>
          <td>${row.soil_temperature ?? '-'} °C</td>
          <td>${row.air_temperature ?? '-'} °C</td>
        </tr>
      `;
    })
    .join('');

  const html = `
    <!DOCTYPE html>

    <html>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <style>
          body {
            font-family: Arial, sans-serif;
            padding: 30px;
            color: #222;
          }

          h1 {
            text-align: center;
            color: #0D5E33;
            margin-bottom: 5px;
          }

          .subtitle {
            text-align: center;
            color: #666;
            margin-bottom: 25px;
          }

          h2 {
            color: #0D5E33;
            margin-top: 25px;
          }

          table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
            font-size: 9px;
          }

          th {
            background-color: #0D5E33;
            color: white;
            padding: 8px;
          }

          td {
            border: 1px solid #ccc;
            padding: 7px;
            text-align: center;
          }

          tr:nth-child(even) {
            background-color: #f5f5f5;
          }

          .info {
            margin-top: 20px;
            padding: 15px;
            background-color: #f0fdf4;
            border: 1px solid #bbf7d0;
          }

          .footer {
            margin-top: 30px;
            text-align: center;
            color: #777;
            font-size: 10px;
          }
        </style>
      </head>

      <body>

        <h1>Soil Quality Report</h1>

        <div class="subtitle">
          Soil Monitoring System
        </div>

        <div class="info">
          <strong>Report Generated:</strong>
          ${new Date().toLocaleString()}
          <br />
          <strong>Total Readings:</strong>
          ${history.length}
        </div>

        <h2>Soil & Nutrient History</h2>

        <table>

          <tr>
            <th>Date</th>
            <th>N</th>
            <th>P</th>
            <th>K</th>
            <th>pH</th>
            <th>Moisture</th>
            <th>Humidity</th>
            <th>Soil Temp</th>
            <th>Air Temp</th>
          </tr>

          ${rows}

        </table>

        <div class="footer">
          Generated by Soil Quality Monitoring System
        </div>

      </body>
    </html>
  `;

  // Generate PDF
  const { uri } = await Print.printToFileAsync({
    html,
  });

  // Open native sharing / save interface
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, {
      mimeType: 'application/pdf',
      dialogTitle: 'Export Soil Quality Report',
      UTI: 'com.adobe.pdf',
    });
  }

  return uri;
}